services:
  nginx:
    expose:
      - 80
      - 443
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - CERT_NAME=default
      - HTTPS_METHOD=noredirect
    volumes:
      - ${NGINX_SSL_PATH}:/etc/ssl/certs:ro
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
    driver: ${NETWORKS_DRIVER}